name: walletwatch_mobile
description: "WalletWatch"
publish_to: "none"
version: 0.4.0+4

environment:
  sdk: "3.4.3"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.7.0
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.4.1
  shared_preferences: ^2.3.1
  flutter_screenutil: 5.9.3
  sign_in_button: 3.2.0
  syncfusion_flutter_datepicker: 26.2.8
  syncfusion_flutter_pdfviewer: 26.2.8
  syncfusion_flutter_charts: 26.2.8
  flutter_advanced_drawer: 1.3.6
  flutter_easyloading: 3.0.5
  flutter_rounded_progress_bar: 0.3.2
  custom_sliding_segmented_control: 1.8.3
  flutter_floating_bottom_bar: 1.2.0
  http: 1.2.2
  flutter_chat_ui: 1.6.14
  dropdown_button2: 2.3.9
  persistent_bottom_nav_bar_v2: 5.3.0
  image_picker: 1.1.2
  flutter_appauth: ^6.0.7
  awesome_notifications: ^0.9.3+1
  permission_handler: 11.3.1
  awesome_notifications_fcm: ^0.9.3+1
  toggle_list: 0.3.1
  animated_custom_dropdown: 3.1.1
  # web_socket_channel: 3.0.1
  go_router: ^14.2.3
  dart_pusher_channels: ^1.2.3
  awesome_bottom_bar: ^1.2.4

  intl: any
  flutter_chat_types: any
  path: any
  http_parser: any
  web_socket_channel: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_background: "assets/icons/ic_launcher_background.png"

flutter_native_splash:
  android: false
  ios: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/paylater/
    - assets/images/government/
    - assets/pdf/
  fonts:
    - family: BottomNavIcons
      fonts:
        - asset: assets/fonts/BottomNavIcons/BottomNavIcons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 900
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo/Baloo-Regular.ttf
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2/Baloo2-Bold.ttf
          weight: 700
    - family: EduTAS
      fonts:
        - asset: assets/fonts/EduTAS/EduTAS-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
