name: wallet_watch
description: "WalletWatch"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.4
  shared_preferences: ^2.2.2
  stroke_text: ^0.0.2
  flutter_tex: ^4.0.6
  flutter_screenutil: ^5.9.0
  sign_in_button: ^3.2.0
  syncfusion_flutter_datepicker: ^25.1.41
  syncfusion_flutter_charts: ^25.1.41
  flutter_advanced_drawer: ^1.3.6
  flutter_easyloading: ^3.0.5
  flutter_rounded_progress_bar: ^0.3.2
  custom_sliding_segmented_control: ^1.8.1
  flutter_floating_bottom_bar: ^1.2.0
  flutter_chat_ui: ^1.6.12
  googleapis: ^13.1.0  
  googleapis_auth: ^1.6.0
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  google_sign_in: ^6.2.1

  intl: any
  flutter_chat_types: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_launcher_icons:
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_background: "assets/icons/ic_launcher_background.png"

flutter_native_splash:
  android: false
  ios: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/paylater/
    - assets/images/government/
  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo/Baloo-Regular.ttf
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2/Baloo2-Bold.ttf
          weight: 700
    - family: EduTAS
      fonts:
        - asset: assets/fonts/EduTAS/EduTAS-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700